In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

/opt/anaconda3/lib/python3.7/site-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

In [26]:
pd.set_option('display.max_columns', None)
df= pd.read_csv('Heart_Disease_Prediction.csv')

In [27]:
df

,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium,Heart Disease
0,70,1,4,130,322,0,2,109,0,2.4,2,3,3,Presence
1,67,0,3,115,564,0,2,160,0,1.6,2,0,7,Absence
2,57,1,2,124,261,0,0,141,0,0.3,1,0,7,Presence
3,64,1,4,128,263,0,0,105,1,0.2,2,1,7,Absence
4,74,0,2,120,269,0,2,121,1,0.2,1,1,3,Absence
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265,52,1,3,172,199,1,0,162,0,0.5,1,0,7,Absence
266,44,1,2,120,263,0,0,173,0,0.0,1,0,7,Absence
267,56,0,2,140,294,0,2,153,0,1.3,2,0,3,Absence
268,57,1,4,140,192,0,0,148,0,0.4,2,0,6,Absence
269,67,1,4,160,286,0,2,108,1,1.5,2,3,3,Presence

In [28]:
def classifier(df):
    if (df['Heart Disease'] == 'Presence'):
        return 1
    else: 
        return 2

In [29]:
df['heartclass']= df.apply(classifier,axis=1)

In [34]:
def cholesterol(df):

    if df['Cholesterol'] < 200:
        return("good")
    elif df['Cholesterol'] > 240:
        return("High")
    else:
        return("Borderline")

In [36]:
df['cholesterolclass']= df.apply(cholesterol,axis=1)

In [43]:
df['cholesterolclass'].value_counts()

High          144
Borderline     87
good           39
Name: cholesterolclass, dtype: int64

In [44]:
df

,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium,Heart Disease,heartclass,cholesterolclass
0,70,1,4,130,322,0,2,109,0,2.4,2,3,3,Presence,1,High
1,67,0,3,115,564,0,2,160,0,1.6,2,0,7,Absence,2,High
2,57,1,2,124,261,0,0,141,0,0.3,1,0,7,Presence,1,High
3,64,1,4,128,263,0,0,105,1,0.2,2,1,7,Absence,2,High
4,74,0,2,120,269,0,2,121,1,0.2,1,1,3,Absence,2,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265,52,1,3,172,199,1,0,162,0,0.5,1,0,7,Absence,2,good
266,44,1,2,120,263,0,0,173,0,0.0,1,0,7,Absence,2,High
267,56,0,2,140,294,0,2,153,0,1.3,2,0,3,Absence,2,High
268,57,1,4,140,192,0,0,148,0,0.4,2,0,6,Absence,2,good
269,67,1,4,160,286,0,2,108,1,1.5,2,3,3,Presence,1,High

In [45]:
def blood(df):

    if df['BP'] > 140:
        return("high")
    else:
        return("good")

In [46]:
df['bloodpressure']= df.apply(blood,axis=1)

In [47]:
df

,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium,Heart Disease,heartclass,cholesterolclass,bloodpressure
0,70,1,4,130,322,0,2,109,0,2.4,2,3,3,Presence,1,High,good
1,67,0,3,115,564,0,2,160,0,1.6,2,0,7,Absence,2,High,good
2,57,1,2,124,261,0,0,141,0,0.3,1,0,7,Presence,1,High,good
3,64,1,4,128,263,0,0,105,1,0.2,2,1,7,Absence,2,High,good
4,74,0,2,120,269,0,2,121,1,0.2,1,1,3,Absence,2,High,good
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265,52,1,3,172,199,1,0,162,0,0.5,1,0,7,Absence,2,good,high
266,44,1,2,120,263,0,0,173,0,0.0,1,0,7,Absence,2,High,good
267,56,0,2,140,294,0,2,153,0,1.3,2,0,3,Absence,2,High,good
268,57,1,4,140,192,0,0,148,0,0.4,2,0,6,Absence,2,good,good
269,67,1,4,160,286,0,2,108,1,1.5,2,3,3,Presence,1,High,high

In [48]:
def blood(df):

    if df['Age'] > 65:
        return("senior")
    else:
        return("nonsenior")

In [ ]:
df['bloodpressure']= df.apply(blood,axis=1)